# exec-once = nwg-dock-hyprland -x -i 40 -p left -a center -ml 8
exec-once = systemctl --user start pipewire wireplumber pipewire-pulse
exec-once = systemctl --user start at-spi-dbus-bus
exec-once = systemctl --user start xdg-desktop-portal
exec-once = pkill -f ws-edge-left.sh; ~/.config/hypr/scripts/ws-edge-left.sh
exec-once = quickshell --path ~/.config/quickshell/shell.qml
exec-once = fcitx5 -d

exec-shutdown = systemctl --user stop pipewire wireplumber pipewire-pulse
exec-shutdown = systemctl --user stop at-spi-dbus-bus
exec-shutdown = systemctl --user stop xdg-desktop-portal
