general {
    lock_cmd = pidof hyprlock || hyprlock --config ~/.config/hypr/hyprlock/hyprlock.conf
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 60
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action dim-display
    on-resume = bash ~/.config/hypr/scripts/idle-power-action restore-display
}

listener {
    timeout = 150
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action kbd-off
    on-resume = bash ~/.config/hypr/scripts/idle-power-action kbd-restore
}

listener {
    timeout = 120
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action lock
}

listener {
    timeout = 330
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action dpms-off
    on-resume = bash ~/.config/hypr/scripts/idle-power-action dpms-on
}

listener {
    timeout = 600
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action suspend-unless-ssh
}
