general {
    lock_cmd = pidof hyprlock || hyprlock --config ~/.config/hypr/hyprlock/hyprlock.conf
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Turn off keyboard backlight. Comment this section out if the device does not have one.
listener {
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on-timeout = ss -H -t state established '( dport = :10005 or sport = :10005 )' | grep -q . || systemctl suspend
}
