# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    repeat_rate = 30
    repeat_delay = 350

    follow_mouse = 0

    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        tap-to-click = true
        tap-and-drag = true
        natural_scroll = false
        clickfinger_behavior = true
        disable_while_typing = true
    }
}
