# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 4
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = false
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = no

    # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    # Default animations, see https://wiki.hypr.land/Configuring/Animations/
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        0,     1,     default
    animation = border,        0,     1,     default
    animation = windows,       0,     1,     default
    animation = windowsIn,     0,     1,     default
    animation = windowsOut,    0,     1,     default
    animation = fadeIn,        0,     1,     default
    animation = fadeOut,       0,     1,     default
    animation = fade,          0,     1,     default
    animation = layers,        0,     1,     default
    animation = layersIn,      0,     1,     default
    animation = layersOut,     0,     1,     default
    animation = fadeLayersIn,  0,     1,     default
    animation = fadeLayersOut, 0,     1,     default
    animation = workspaces,    0,     1,     default
    animation = workspacesIn,  0,     1,     default
    animation = workspacesOut, 0,     1,     default
    animation = zoomFactor,    0,     1,     default
}
