# exec-once = waybar & hyprpaper & firefox
exec-once = foot --server
exec-once = waybar
exec-once = dunst
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = fcitx5 -d
exec-once = pkill hypridle; hypridle --config ~/.config/hypr/conf/current/hypridle.conf
exec-once = bash ~/.config/hypr/scripts/battery-suspend-10
