general {
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 60
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action battery-dim-display
    on-resume = bash ~/.config/hypr/scripts/idle-power-action battery-restore-display
}

listener {
    timeout = 150
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action battery-kbd-off
    on-resume = bash ~/.config/hypr/scripts/idle-power-action battery-kbd-restore
}

listener {
    timeout = 180
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action ac-dim-display
    on-resume = bash ~/.config/hypr/scripts/idle-power-action ac-restore-display
}

listener {
    timeout = 300
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action battery-lock
}

listener {
    timeout = 300
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action ac-kbd-off
    on-resume = bash ~/.config/hypr/scripts/idle-power-action ac-kbd-restore
}

listener {
    timeout = 480
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action battery-dpms-off
    on-resume = bash ~/.config/hypr/scripts/idle-power-action dpms-on
}

listener {
    timeout = 600
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action battery-shutdown
}

listener {
    timeout = 600
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action ac-lock
}

listener {
    timeout = 900
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action ac-dpms-off
    on-resume = bash ~/.config/hypr/scripts/idle-power-action dpms-on
}

listener {
    timeout = 1800
    on-timeout = bash ~/.config/hypr/scripts/idle-power-action ac-shutdown
}
