windowrule {
    name = float-time-control-popup

    match:class = time-control-popup

    float = yes
    center = yes
    size = 900 560
}

windowrule {
    name = float-wifi-connect-popup

    match:class = wifi-connect-popup

    float = yes
    center = yes
    size = 980 420
}

windowrule {
    name = float-yazi

    match:class = ^yazi$

    float = yes
    center = yes
    size = 1100 720
}
