#!/usr/bin/env bash

set -eu

POWER_SUPPLY_DIR="/sys/class/power_supply"

for online_file in "$POWER_SUPPLY_DIR"/AC*/online "$POWER_SUPPLY_DIR"/ADP*/online "$POWER_SUPPLY_DIR"/ACAD/online; do
    if [ -r "$online_file" ] && [ "$(cat "$online_file")" = "1" ]; then
        exit 0
    fi
done

systemctl suspend
