local M = {}

function M.setup(ctx)
  local _ENV = ctx
  local home = os.getenv("HOME") or "~"

  bind(main_mod .. " + P", exec(launcher_command))
  bind(main_mod .. " + SHIFT + P", exec(power_menu))
  bind(main_mod .. " + grave", exec("quickshell ipc call topbar toggle"))
  bind(hyper .. " + SHIFT + N", exec(shell_ui_command .. " control-center"))
  bind(hyper .. " + CTRL + N", exec(shell_ui_command .. " settings"))
  bind(main_mod .. " + Return", exec(terminal))
  bind(main_mod .. " + SHIFT + Return", exec("foot"))
  bind(main_mod .. " + SHIFT + C", hl.dsp.window.close())
  bind(main_mod .. " + SHIFT + Q", hl.dsp.exit())
  bind(main_mod .. " + E", exec("emacsclient --eval '(emacs-everywhere)'"))
  bind(main_mod .. " + V", exec("wl-paste | xdotool type --file -"))
  bind(main_mod .. " + up", function()
    focus_direction("up")
  end)
  bind(main_mod .. " + down", function()
    focus_direction("down")
  end)
  bind(main_mod .. " + left", function()
    focus_direction("left")
  end)
  bind(main_mod .. " + right", function()
    focus_direction("right")
  end)

  bind(main_mod .. " + SHIFT + up", function()
    swap_direction("up")
  end)
  bind(main_mod .. " + SHIFT + down", function()
    swap_direction("down")
  end)
  bind(main_mod .. " + SHIFT + left", function()
    swap_direction("left")
  end)
  bind(main_mod .. " + SHIFT + right", function()
    swap_direction("right")
  end)

  bind(main_mod .. " + CTRL + up", function()
    move_window_to_monitor("u", true)
  end)
  bind(main_mod .. " + CTRL + down", function()
    move_window_to_monitor("d", true)
  end)
  bind(main_mod .. " + CTRL + left", function()
    move_window_to_monitor("l", true)
  end)
  bind(main_mod .. " + CTRL + right", function()
    move_window_to_monitor("r", true)
  end)
  bind(main_mod .. " + CTRL + SHIFT + up", function()
    move_window_to_empty_workspace_on_monitor("u")
  end)
  bind(main_mod .. " + CTRL + SHIFT + down", function()
    move_window_to_empty_workspace_on_monitor("d")
  end)
  bind(main_mod .. " + CTRL + SHIFT + left", function()
    move_window_to_empty_workspace_on_monitor("l")
  end)
  bind(main_mod .. " + CTRL + SHIFT + right", function()
    move_window_to_empty_workspace_on_monitor("r")
  end)

  hl.define_submap("swap-workspace", function()
    for i = 1, 9 do
      local workspace_id = i
      bind(tostring(i), function()
        swap_current_workspace_with(workspace_id)
        dispatch(hl.dsp.submap("reset"))
      end)
    end

    bind("Escape", hl.dsp.submap("reset"))
    bind("catchall", hl.dsp.submap("reset"))
  end)

  hl.define_submap("window-picker", function()
    for i = 1, 9 do
      local index = i
      bind(tostring(i), function()
        activate_window_picker_candidate(index)
      end)
    end

    bind("Escape", hl.dsp.submap("reset"))
    bind("catchall", hl.dsp.submap("reset"))
  end)

  bind(mod_alt .. " + SHIFT + W", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
  bind(mod_alt .. " + SHIFT + S", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })
  bind(mod_alt .. " + SHIFT + A", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
  bind(mod_alt .. " + SHIFT + D", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })

  bind(hyper .. " + up", hl.dsp.focus({ monitor = "u" }))
  bind(hyper .. " + down", hl.dsp.focus({ monitor = "d" }))
  bind(hyper .. " + left", hl.dsp.focus({ monitor = "l" }))
  bind(hyper .. " + right", hl.dsp.focus({ monitor = "r" }))
  bind(hyper .. " + SHIFT + up", function()
    move_window_to_monitor("u", true)
  end)
  bind(hyper .. " + SHIFT + down", function()
    move_window_to_monitor("d", true)
  end)
  bind(hyper .. " + SHIFT + left", function()
    move_window_to_monitor("l", true)
  end)
  bind(hyper .. " + SHIFT + right", function()
    move_window_to_monitor("r", true)
  end)

  bind(main_mod .. " + Space", cycle_layout_or_restore_tabbed_group)
  bind(main_mod .. " + SHIFT + Space", force_columns_layout)
  bind(main_mod .. " + CTRL + Space", gather_workspace_into_tabbed_group)
  bind(main_mod .. " + bracketright", monocle_next)
  bind(main_mod .. " + bracketleft", monocle_prev)
  bind(main_mod .. " + T", hl.dsp.window.float({ action = "disable" }))
  bind(main_mod .. " + O", toggle_pinned_active_window)
  bind(main_mod .. " + F", hl.dsp.window.fullscreen())
  bind(main_mod .. " + M", minimize_active_window)
  bind(main_mod .. " + SHIFT + M", restore_last_minimized)
  bind(main_mod .. " + CTRL + SHIFT + M", function()
    enter_window_picker("minimized")
  end)
  bind(main_mod .. " + SHIFT + equal", schedule_nstack_count_update)
  bind(main_mod .. " + CTRL + M", hl.dsp.window.toggle_swallow())
  bind(main_mod .. " + SHIFT + E", function()
    move_to_next_empty_workspace(true)
  end)
  bind(main_mod .. " + CTRL + E", function()
    move_to_next_empty_workspace(false)
  end)
  bind(main_mod .. " + apostrophe", focus_next_class)
  bind(mod_alt .. " + W", show_active_window_info)

  bind(main_mod .. " + X", exec("rofi_command.sh"))
  bind(main_mod .. " + SHIFT + X", hl.dsp.workspace.toggle_special("NSP"))
  bind(mod_alt .. " + C", function()
    toggle_scratchpad("codex")
  end)
  bind(mod_alt .. " + E", function()
    toggle_scratchpad("element")
  end)
  bind(mod_alt .. " + H", function()
    toggle_scratchpad("htop")
  end)
  bind(mod_alt .. " + K", function()
    toggle_scratchpad("slack")
  end)
  bind(mod_alt .. " + M", function()
    toggle_scratchpad("messages")
  end)
  bind(mod_alt .. " + S", function()
    toggle_scratchpad("spotify")
  end)
  bind(mod_alt .. " + T", function()
    toggle_scratchpad("transmission")
  end)
  bind(mod_alt .. " + V", function()
    toggle_scratchpad("volume")
  end)
  bind(mod_alt .. " + grave", function()
    toggle_scratchpad("dropdown")
  end)
  bind(mod_alt .. " + Space", minimize_other_classes)
  bind(mod_alt .. " + SHIFT + Space", restore_focused_class)
  bind(mod_alt .. " + Return", restore_all_minimized)

  for i = 1, 9 do
    local workspace = tostring(i)
    bind(main_mod .. " + " .. workspace, hl.dsp.focus({ workspace = workspace, on_current_monitor = true }))
    bind(main_mod .. " + SHIFT + " .. workspace, hl.dsp.window.move({ workspace = workspace, follow = false }))
    bind(main_mod .. " + CTRL + " .. workspace, function()
      dispatch(hl.dsp.window.move({ workspace = workspace, follow = false }))
      dispatch(hl.dsp.focus({ workspace = workspace, on_current_monitor = true }))
    end)
  end

  bind(main_mod .. " + Z", hl.dsp.focus({ monitor = "+1" }))
  bind(main_mod .. " + SHIFT + Z", hl.dsp.window.move({ monitor = "+1" }))
  bind(main_mod .. " + mouse_down", function()
    cycle_workspace(1)
  end)
  bind(main_mod .. " + mouse_up", function()
    cycle_workspace(-1)
  end)
  bind(hyper .. " + E", focus_next_empty_workspace)
  bind(hyper .. " + 5", enter_workspace_swap_mode)
  bind(hyper .. " + G", gather_focused_class)

  bind(main_mod .. " + I", exec("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
  bind(main_mod .. " + K", exec("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
  bind(main_mod .. " + U", exec("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
  bind(main_mod .. " + semicolon", exec("playerctl play-pause"))
  bind(main_mod .. " + L", exec("playerctl next"))
  bind(main_mod .. " + J", exec("playerctl previous"))

  bind("XF86AudioPlay", exec("playerctl play-pause"))
  bind("XF86AudioPause", exec("playerctl play-pause"))
  bind("XF86AudioNext", exec("playerctl next"))
  bind("XF86AudioPrev", exec("playerctl previous"))
  bind("XF86AudioRaiseVolume", exec("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
  bind("XF86AudioLowerVolume", exec("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
  bind("XF86AudioMute", exec("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
  bind("XF86MonBrightnessUp", exec("brightness.sh up"), { repeating = true })
  bind("XF86MonBrightnessDown", exec("brightness.sh down"), { repeating = true })

  bind(hyper .. " + V", exec([[cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy]]))
  bind(hyper .. " + P", exec("rofi-pass"))
  bind(hyper .. " + H", exec([[grim -g "$(slurp)" - | swappy -f -]]))
  bind(hyper .. " + C", exec("rofi_tmcodex.sh"))
  bind(hyper .. " + SHIFT + C", exec("rofi_tmcodex.sh resume"))
  bind(hyper .. " + L", exec("pidof hyprlock || hyprlock --config ~/.config/hypr/hyprlock/hyprlock.conf --grace 0 --immediate-render"))
  bind(hyper .. " + SHIFT + L", exec("bash ~/.config/hypr/scripts/layout-picker"))
  bind(hyper .. " + K", exec("bash ~/.config/hypr/scripts/process-kill-picker"))
  bind(hyper .. " + SHIFT + K", exec("bash ~/.config/hypr/scripts/process-kill-all-picker"))
  bind(hyper .. " + R", exec("bash ~/.config/hypr/scripts/systemd-picker"))
  bind(hyper .. " + slash", function()
    hl.exec_cmd("toggle_taffybar")
    refresh_monitor_reserved_cache(0.25)
    refresh_active_scratchpad_geometries_later(600)
  end)
  bind(hyper .. " + I", exec("bash ~/.config/hypr/scripts/audio-device-picker source"))
  bind(hyper .. " + O", exec("bash ~/.config/hypr/scripts/audio-device-picker sink"))
  bind(hyper .. " + comma", exec("rofi_wallpaper.sh"))
  bind(hyper .. " + SHIFT + comma", exec(home .. "/dotfiles/dotfiles/lib/bin/neowall-wallpaper toggle"))
  bind(hyper .. " + Y", exec("rofi_agentic_skill"))
  bind(main_mod .. " + R", exec("hyprctl reload"))

  bind(main_mod .. " + mouse:272", float_and_drag_active_window)
  bind(main_mod .. " + mouse:273", float_and_resize_active_window)
end

return M
